In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

### merging columns on the basis of column - title of movie

In [7]:
newdf=movies.merge(credits,on='title')

In [8]:
newdf.shape

(4809, 23)

### keep only the useful columns/features

In [9]:
newdf.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
newdf.head(1)['keywords'].values

array(['[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'],
      dtype=object)

In [11]:
newdf.original_language.value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [12]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

### selected features
genres,id,keywords,title,overview,cast,crew

In [13]:
movies=newdf[['movie_id','title','genres','keywords','overview','cast','crew']]

In [14]:
movies.head(1)

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

### eliminate missing data

In [15]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [16]:
movies.dropna(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\3786870272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [17]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
overview    0
cast        0
crew        0
dtype: int64

In [18]:
movies.duplicated().sum()

0

In [19]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
# convert this to a different form
# ['action','adventure','fantasy','scifi']

In [21]:
def convert(obj):
    L=[]
    for i in obj:
        L.append(i['name'])
    return L

In [22]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

TypeError: string indices must be integers, not 'str'

In [23]:
# now we need to convert this string of list to a list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [24]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [25]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [26]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [27]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\1567952790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [28]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [29]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [31]:
movies['keywords']=movies['keywords'].apply(convert)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\1621871954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

In [32]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [34]:
def convertcast(obj):
    L=[]
    for i in range(3):
        if i<len(ast.literal_eval(obj)):
            L.append(ast.literal_eval(obj)[i]['name'])
    return L

In [35]:
convertcast(movies.iloc[0].cast)

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [36]:
movies['cast'].apply(convertcast)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [37]:
movies['cast']=movies['cast'].apply(convertcast)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\2913297907.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convertcast)

In [47]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [51]:
movies.iloc[0].crew

['James Cameron']

In [49]:
def extract(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [50]:
extract(movies.iloc[0].crew)

ValueError: malformed node or string: ['James Cameron']

In [42]:
movies['crew'].apply(extract)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [43]:
movies['crew']=movies['crew'].apply(extract)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\1334595674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(extract)

In [52]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [45]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [53]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [54]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\1104793012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x:x.split())

In [55]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

### remove the spaces between words to make it a single entity

In [56]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [73]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\HP\AppData\Local\Temp\ipykernel_23660\568931677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\HP\AppData\Local\Temp\ipykernel_23660\568931677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\HP\AppData\Local\Temp\ipykernel_23660\568931677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\HP\AppData\Local\Temp\ipykernel_23660\568931677.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [57]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [58]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\694219746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [59]:
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [60]:
final_df=movies[['movie_id','title','tags']]

In [82]:
final_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [61]:
final_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [62]:
# convert to a string
final_df['tags']=final_df['tags'].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\3340181368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(lambda x:" ".join(x))

In [63]:
final_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [64]:
final_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [65]:
# convert all in lowercase letters
final_df['tags']=final_df['tags'].apply(lambda x:x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\3827165314.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(lambda x:x.lower())

In [66]:
final_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [67]:
# do text vectorization
final_df.shape

(4806, 3)

In [69]:
import nltk

In [70]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [71]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [72]:
stem(final_df['tags'][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d sam worthington zoe saldana sigourney weaver jame cameron'

In [73]:
final_df['tags']=final_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_22324\3542233429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(stem)

In [115]:
final_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [74]:
# we will use bag of words 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [75]:
vectors=cv.fit_transform(final_df['tags'])

In [76]:
vectors

<4806x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 179434 stored elements in Compressed Sparse Row format>

In [77]:
array_representation=vectors.toarray()

In [78]:
array_representation

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [79]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [80]:
# calculate the similarity between these vectors
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(array_representation)

In [81]:
similarity

array([[1.        , 0.06692745, 0.06554735, ..., 0.04442617, 0.03244428,
        0.        ],
       [0.06692745, 1.        , 0.04167571, ..., 0.03766218, 0.        ,
        0.01756008],
       [0.06554735, 0.04167571, 1.        , ..., 0.01844278, 0.0808122 ,
        0.        ],
       ...,
       [0.04442617, 0.03766218, 0.01844278, ..., 1.        , 0.03651484,
        0.03108349],
       [0.03244428, 0.        , 0.0808122 , ..., 0.03651484, 1.        ,
        0.06810052],
       [0.        , 0.01756008, 0.        , ..., 0.03108349, 0.06810052,
        1.        ]])

In [82]:
similarity.shape

(4806, 4806)

In [83]:
similarity[0]

array([1.        , 0.06692745, 0.06554735, ..., 0.04442617, 0.03244428,
       0.        ])

In [85]:
final_df['title']=='Avatar'

0        True
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4806, dtype: bool

In [88]:
final_df[final_df['title']=='Avatar'].index[0]

0

In [89]:
sorted(similarity[0],reverse=True)

[0.9999999999999999,
 0.49356764739637354,
 0.4113063728303113,
 0.38807121827489494,
 0.3879852850993631,
 0.380442955126341,
 0.3776782946782564,
 0.3742636563667588,
 0.35840861465369933,
 0.3421708589084696,
 0.3311330892662609,
 0.32481131806711666,
 0.3248113180671166,
 0.3247499344668203,
 0.3231104224953257,
 0.3222129681246328,
 0.3162994973926084,
 0.312640945658523,
 0.3121952705272313,
 0.3084235851091745,
 0.30588764516074896,
 0.30442954117128224,
 0.3008967382970351,
 0.2987264917430253,
 0.2974059387397313,
 0.2949687762244818,
 0.2938769068226293,
 0.29314232661238443,
 0.29139711855430955,
 0.29135827337403253,
 0.2896811091620759,
 0.28867513459481287,
 0.28791446098121787,
 0.2867696673382022,
 0.2866297455600074,
 0.2845551966122361,
 0.2838874869788344,
 0.27912109783679506,
 0.2752988806446741,
 0.2678577339568831,
 0.2605842192811105,
 0.2604940361258638,
 0.26013299085723596,
 0.25958499574503335,
 0.25605197407973057,
 0.25391668753850405,
 0.25387276871303704,
 0.25362863675089403,
 0.2533558548547658,
 0.24722569302909875,
 0.24722569302909872,
 0.24678382369818672,
 0.2445579940222592,
 0.24366985862022406,
 0.24309485018510557,
 0.24165972609347458,
 0.24099009325151113,
 0.24002133617819923,
 0.2364763257317293,
 0.23475647508309563,
 0.2342460684935891,
 0.23366150977305886,
 0.23366150977305886,
 0.23308661869922598,
 0.23308661869922598,
 0.23288666826750604,
 0.2294157338705617,
 0.22790142204853647,
 0.22663483432464554,
 0.22213082915965962,
 0.22213082915965962,
 0.2204856030790368,
 0.2204155075111935,
 0.2176428750330035,
 0.21371260356627755,
 0.21341639745917707,
 0.2130071614211525,
 0.21179343552183932,
 0.21052631578947367,
 0.20991342856239587,
 0.20991342856239587,
 0.2074364287612964,
 0.20561572340611634,
 0.20519567041703082,
 0.20441907985364974,
 0.20138310507789547,
 0.20138310507789547,
 0.20078234442307638,
 0.20073876713674155,
 0.19927028533261387,
 0.19918863762856526,
 0.19664205760333864,
 0.19619314913492367,
 0.19619314913492364,
 0.19564639521780738,
 0.195099743142927,
 0.1946978894863169,
 0.1938916835823703,
 0.19088542889273327,
 0.19001047197680243,
 0.1860807318911967,
 0.18560646746692377,
 0.18560646746692377,
 0.185539010998235,
 0.1842105263157894,
 0.18394180184548975,
 0.1835325870964494,
 0.1830104449656007,
 0.18249909877210785,
 0.18074256993863336,
 0.1792043073268497,
 0.17920430732684967,
 0.17914359097500465,
 0.17875929966870285,
 0.17844356324383875,
 0.17660431427533915,
 0.17624204863381399,
 0.1749783098183389,
 0.17497830981833887,
 0.17492785713532988,
 0.17453202440084276,
 0.17342199390482396,
 0.1720618004029213,
 0.17099639201419237,
 0.17040572913692198,
 0.17040572913692198,
 0.17036656890909552,
 0.17013926184468012,
 0.17013926184468012,
 0.16861331835836557,
 0.1675415633166782,
 0.16747265870207706,
 0.16747265870207706,
 0.16747265870207703,
 0.16742770563222895,
 0.16692446522239715,
 0.16556654463313047,
 0.16556654463313047,
 0.16531163063339513,
 0.1642706150496122,
 0.16427061504961218,
 0.16390251702679645,
 0.16386838133611553,
 0.1630554699247529,
 0.16289594138375035,
 0.16222142113076254,
 0.16222142113076252,
 0.1615552112476628,
 0.16122923187750418,
 0.16122923187750418,
 0.16122923187750418,
 0.16122923187750418,
 0.16062314155080884,
 0.15974461276617435,
 0.1590711907439444,
 0.15897016107942197,
 0.15897016107942194,
 0.15806712450288418,
 0.15789473684210523,
 0.1577233170360112,
 0.15756337291581363,
 0.15650535813672986,
 0.15650535813672986,
 0.1556357543698668,
 0.15511334686589623,
 0.15452877499092174,
 0.1541517600345829,
 0.1538057703910978,
 0.15301409312053071,
 0.15242624470826976,
 0.15193428136569098,
 0.15174424466672098,
 0.15086285728094284,
 0.15058675831730728,
 0.15018785229652767,
 0.14975189244419534,
 0.14933692277237473,
 0.14930178053803184,
 0.14930178053803184,
 0.14912022701586516,
 0.14910501299480672,
 0.14886458551295736,
 0.14870296936986566,
 0.14808721943977307,
 0.14768094372379,
 0.14748154320250398,
 0.14748154320250398,
 0.14686837386151166,
 0.14686837386151166,
 0.14599927901768628,
 0.14599927901768628,
 0.14567913668701624,
 0.14552644042288465,
 0.14456082739572798,
 0.14429582107316452,
 0.1433848336691011,
 0.14316407166954997,
 0.14273582042094193,
 0.14227759830611805,
 0.14180703562423225,
 0.14180703562423225,
 0.14180703562423225,
 0.14159846508095772,
 0.14159846508095772,
 0.14159846508095772,
 0.1404878717372541,
 0.1399422857082639,
 0.1399422857082639,
 0.1391037210186643,
 0.1391037210186643,
 0.13834289277321493,
 0.13834289277321493,
 0.13809204416652687,
 0.13770565818881086,
 0.13767219793848368,
 0.13685996549319585,
 0.13685996549319585,
 0.13679711361135388,
 0.1361331925293325,
 0.13572417850765922,
 0.1357241785076592,
 0.13555692745397502,
 0.13530201829834765,
 0.13497638119975425,
 0.13497638119975425,
 0.13450689671224256,
 0.1343320988518935,
 0.13425540338526365,
 0.13382584475782766,
 0.13245323570650439,
 0.13245323570650439,
 0.13245323570650436,
 0.13245323570650436,
 0.132005000120825,
 0.13111122301831463,
 0.13109470506889243,
 0.13109470506889243,
 0.13006649542861798,
 0.13006649542861798,
 0.13006649542861795,
 0.12977713690461,
 0.1290564332299168,
 0.1290564332299168,
 0.128920512778062,
 0.12811501208373438,
 0.12804983847550624,
 0.12725695259515554,
 0.12725695259515554,
 0.12725695259515554,
 0.12695834376925205,
 0.12695834376925202,
 0.12667364798453495,
 0.12612416730102238,
 0.12565617248750865,
 0.12540051368250327,
 0.1251933489167979,
 0.12519334891679787,
 0.12487810821089251,
 0.12369267399882333,
 0.12361284651454937,
 0.1233919118490934,
 0.12313775728090239,
 0.12297974198582043,
 0.12227899701112961,
 0.1222789970111296,
 0.1216660658480719,
 0.1216660658480719,
 0.12166606584807188,
 0.12105003117656304,
 0.12082986304673729,
 0.12082986304673729,
 0.11980845957463077,
 0.11969747440993465,
 0.11969747440993464,
 0.11969747440993464,
 0.11959121830873498,
 0.11946953821789978,
 0.11946953821789978,
 0.11920791213585391,
 0.11846977555181847,
 0.11846977555181845,
 0.11846977555181845,
 0.11846977555181845,
 0.11846977555181845,
 0.1183892660110542,
 0.11838926601105419,
 0.11768778828946262,
 0.11764957176360048,
 0.11764957176360048,
 0.11764957176360048,
 0.11764957176360047,
 0.11749469908920933,
 0.11717498502967603,
 0.11712303424679454,
 0.11654330934961299,
 0.11654330934961299,
 0.1164681928033949,
 0.11615078990692515,
 0.11615078990692514,
 0.11615078990692514,
 0.11589658124319134,
 0.11589658124319133,
 0.11566778213857246,
 0.11561466260321597,
 0.11561466260321597,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528087,
 0.11470786693528086,
 0.11382207864489445,
 0.11314714296070713,
 0.11295649894498098,
 0.11295649894498097,
 0.11243619908556621,
 0.11243619908556621,
 0.11194341570991126,
 0.11164843913471803,
 0.11134983352076111,
 0.11134983352076111,
 0.1113498335207611,
 0.1113498335207611,
 0.111323406598941,
 0.11128297681493145,
 0.11128297681493143,
 0.1106817677872384,
 0.11047363533322149,
 0.11047363533322148,
 0.11037769642208697,
 0.11037769642208697,
 0.11029436104106954,
 0.11029436104106954,
 0.11029436104106953,
 0.11024280153951839,
 0.11020775375559674,
 0.11020775375559674,
 0.10968169942141634,
 0.10926834468453095,
 0.10926834468453095,
 0.10926834468453095,
 0.10882143751650175,
 0.10838874619051497,
 0.10838874619051497,
 0.10838874619051497,
 0.10838874619051497,
 0.10827043935570554,
 0.10827043935570553,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.108147614087175,
 0.108147614087175,
 0.108147614087175,
 0.1074861545850028,
 0.10740432270821092,
 0.10729938440986901,
 0.10729938440986901,
 0.10729938440986901,
 0.10715994395536395,
 0.10705186531570646,
 0.10667614941253299,
 0.10650358071057624,
 0.10650358071057624,
 0.1064809179630677,
 0.1064809179630677,
 0.10635399695598369,
 0.10635399695598369,
 0.10619884881071828,
 0.10619884881071828,
 0.10591900946051636,
 0.10526315789473682,
 0.10526315789473682,
 0.10495671428119792,
 0.10495671428119792,
 0.10471347707292387,
 0.10471347707292386,
 0.10457739712320041,
 0.1039048666932262,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10375716957991118,
 0.10375716957991118,
 0.10366105360784116,
 0.10366105360784114,
 0.10366105360784114,
 0.1032370802417528,
 0.10280786170305815,
 0.10259783520851543,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.10197539568091137,
 0.10147651372376074,
 0.10147651372376074,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10138838820672658,
 0.10133891838762797,
 0.10116282977781398,
 0.10116282977781396,
 0.1007265930331758,
 0.10039117221153819,
 0.10039117221153819,
 0.10039117221153819,
 0.10039117221153818,
 0.10036938356837077,
 0.10036938356837077,
 0.10036938356837077,
 0.10036938356837076,
 0.10012523486435176,
 0.10012523486435176,
 0.10012523486435176,
 0.09984038297885897,
 0.09984038297885897,
 0.09959431881428264,
 0.09959431881428263,
 0.09959431881428263,
 0.09895413919905867,
 0.09895413919905867,
 0.0983611844205792,
 0.0983611844205792,
 0.0983611844205792,
 0.09832102880166932,
 0.09832102880166932,
 0.09832102880166932,
 0.09809657456746182,
 0.09733285267845751,
 0.09694584179118515,
 0.09694584179118515,
 0.09694584179118515,
 0.09694584179118515,
 0.09673016668133488,
 0.09637388493048532,
 0.09637388493048532,
 0.09637388493048532,
 0.09637388493048532,
 0.09637388493048532,
 0.09619721404877635,
 0.09597148699373931,
 0.09597148699373931,
 0.0959714869937393,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09567297464698797,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09558988911273406,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636666,
 0.09544271444636665,
 0.09544271444636665,
 0.09529323477053277,
 0.09529323477053275,
 0.09529323477053275,
 0.09464970485606018,
 0.09462916232627815,
 0.09462916232627813,
 0.09453802374948818,
 0.09453802374948816,
 0.09453802374948816,
 0.09453802374948816,
 0.09453802374948816,
 0.09431035367836321,
 0.09428928580058928,
 0.09428928580058928,
 0.09397878236968457,
 0.0936585811581694,
 0.09365858115816939,
 0.09365858115816939,
 0.09334163073596637,
 0.09334163073596637,
 0.09334163073596637,
 0.09308574042571362,
 0.09304036594559835,
 0.09304036594559835,
 0.09280323373346189,
 0.09280323373346189,
 0.09280323373346189,
 0.09280323373346189,
 0.09271726499455304,
 0.09222859518214328,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274487,
 0.09197090092274486,
 0.09183979479633063,
 0.09183979479633061,
 0.0917662935482247,
 0.0917662935482247,
 0.0917662935482247,
 0.09176629354822469,
 0.09154684414630487,
 0.09150522248280035,
 0.09131087488821056,
 0.09116056881941459,
 0.09116056881941459,
 0.09116056881941459,
 0.09091675835657292,
 0.09089518086526238,
 0.09086217008485094,
 0.09086217008485092,
 0.09068453126375145,
 0.09068453126375145,
 0.09068453126375145,
 0.09037128496931668,
 0.09037128496931668,
 0.09033950326094177,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.0899842541331695,
 0.08977310580745097,
 0.08960215366342483,
 0.08960215366342483,
 0.08957179548750233,
 0.08957179548750233,
 0.08957179548750233,
 0.08957179548750233,
 0.08921722983855178,
 0.08918325397005952,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386385,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08885233166386383,
 0.08849904067559858,
 0.08849904067559858,
 0.08849904067559858,
 0.08849904067559858,
 0.08849904067559858,
 0.08849904067559858,
 0.08830215713766958,
 0.08830215713766958,
 0.08830215713766958,
 0.08820139006486122,
 0.08813576890402881,
 0.08812102431690699,
 0.08812102431690699,
 0.08812102431690699,
 0.08812102431690699,
 0.08746392856766494,
 0.08746392856766494,
 0.08746392856766494,
 0.08746392856766494,
 0.08740748201220974,
 0.08740748201220974,
 0.08709270531385191,
 0.08671099695241198,
 0.08671099695241197,
 0.08658487179917634,
 0.08646430798325933,
 0.08646430798325933,
 0.08608581939007431,
 0.08603090020146066,
 0.08603090020146066,
 0.08603090020146066,
 0.08603090020146065,
 0.08603090020146065,
 0.08559529790779072,
 0.08549819600709618,
 0.08549819600709618,
 0.08549819600709618,
 0.08549819600709618,
 0.08549819600709618,
 0.08549819600709618,
 0.08549819600709618,
 0.08536655898367083,
 0.08536655898367082,
 0.08536655898367082,
 0.08536655898367082,
 0.08536655898367082,
 0.08536655898367082,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08520286456846099,
 0.08511306704001456,
 0.08456376143646728,
 0.08456376143646728,
 0.08456376143646728,
 0.08433490104000932,
 0.08408277820068158,
 0.08408277820068157,
 0.08408277820068155,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.0837707816583391,
 0.08371385281611449,
 0.08371385281611447,
 0.08371385281611447,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628182,
 0.08365931017628181,
 0.08365931017628181,
 0.08365931017628181,
 0.08365931017628181,
 0.08365931017628181,
 0.08346223261119859,
 0.08346223261119859,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08326256191221612,
 0.08326256191221612,
 0.08285522649991611,
 0.08285522649991611,
 0.08285522649991611,
 0.08285522649991611,
 0.08285522649991611,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08278327231656524,
 0.08240856434303291,
 0.08240856434303291,
 0.08226127456606226,
 0.08226127456606226,
 0.08226127456606225,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08193419066805777,
 0.08167991551759951,
 0.08167991551759951,
 0.08152773496237643,
 0.08111071056538127,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.08111071056538126,
 0.0805532420311582,
 0.0805532420311582,
 0.0805532420311582,
 0.08031157077540443,
 0.08031157077540443,
 0.08031157077540443,
 0.08017658293783157,
 0.08000711205939974,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07953559537197222,
 0.07953559537197222,
 0.07953559537197222,
 0.07953559537197222,
 0.07950439882424458,
 0.07950439882424457,
 0.07947194142390261,
 0.07911751380897428,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07894736842105261,
 0.07878168645790681,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07836039099693788,
 0.07804881763180782,
 0.07804881763180782,
 0.07804881763180782,
 0.07792865001991965,
 0.07780509096008809,
 0.07762459638285141,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07755667343294811,
 0.07743385993795009,
 0.07733602811121824,
 0.07733602811121824,
 0.07733602811121824,
 0.0770085628656519,
 0.07694837640638655,
 0.07694837640638655,
 0.07694837640638655,
 0.07690914705058355,
 0.07664241743562072,
 0.07664241743562072,
 0.07664241743562072,
 0.07664241743562072,
 0.07664241743562072,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07621312235413488,
 0.07596714068284549,
 0.07596714068284549,
 0.07596714068284549,
 0.07568756326085964,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07530940414109723,
 0.07530940414109723,
 0.07530940414109723,
 0.07530940414109723,
 0.07530940414109723,
 0.07509392614826382,
 0.07509392614826382,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07466846138618737,
 0.07455250649740336,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.07443229275647868,
 0.074215604399294,
 0.074215604399294,
 0.07404360971988654,
 0.07378784519149227,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07343418693075583,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07336739820667776,
 0.07299591532245146,
 0.07299591532245146,
 0.07295405746286962,
 0.07283956834350812,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07225916412700999,
 0.07225916412700999,
 0.07225916412700999,
 0.07175473098524099,
 0.07175473098524099,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07175473098524097,
 0.07169241683455055,
 0.07169241683455055,
 0.07169241683455055,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07165743639000186,
 0.07136791021047097,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305903,
 0.07113879915305901,
 0.07098727864204514,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07059781184061312,
 0.07024393586862705,
 0.07024393586862705,
 0.07024393586862705,
 0.07024393586862705,
 0.07006898183390131,
 0.07006898183390131,
 0.06997114285413195,
 0.06997114285413195,
 0.06997114285413195,
 0.06955186050933215,
 0.06955186050933215,
 0.06955186050933215,
 0.06955186050933215,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.0691073690718941,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06904602208326342,
 0.06882472016116853,
 0.06882472016116853,
 0.06882472016116853,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06855106213838522,
 0.06848315616615792,
 0.06848315616615792,
 0.06839855680567694,
 0.06839855680567694,
 0.06806659626466625,
 0.06806659626466625,
 0.06806659626466625,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06765100914917382,
 0.06759225880448438,
 0.06759225880448438,
 0.06759225880448438,
 0.06759225880448438,
 0.06748819059987712,
 0.06748819059987712,
 0.06748819059987712,
 0.06748819059987712,
 0.06748819059987712,
 0.06716604942594676,
 0.06712770169263182,
 0.06712770169263182,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06692744814102546,
 0.06684847767323795,
 0.06667259338283311,
 0.06667259338283311,
 0.06667259338283311,

In [90]:
list(enumerate(similarity[0]))

[(0, 0.9999999999999999),
 (1, 0.06692744814102546),
 (2, 0.06554735253444621),
 (3, 0.04335549847620599),
 (4, 0.28791446098121787),
 (5, 0.1433848336691011),
 (6, 0.035121967934313526),
 (7, 0.11654330934961299),
 (8, 0.03771571432023571),
 (9, 0.10036938356837077),
 (10, 0.11029436104106954),
 (11, 0.07733602811121824),
 (12, 0.054410718758250876),
 (13, 0.024738534799764667),
 (14, 0.1577233170360112),
 (15, 0.06855106213838522),
 (16, 0.10366105360784114),
 (17, 0.108147614087175),
 (18, 0.13006649542861798),
 (19, 0.06855106213838522),
 (20, 0.05528134553975607),
 (21, 0.06362847629757777),
 (22, 0.04415107856883479),
 (23, 0.05309942440535914),
 (24, 0.04518564248465834),
 (25, 0.06309151753013043),
 (26, 0.16427061504961218),
 (27, 0.20519567041703082),
 (28, 0.06955186050933215),
 (29, 0.052288698561600205),
 (30, 0.09809657456746182),
 (31, 0.14808721943977307),
 (32, 0.07894736842105261),
 (33, 0.09558988911273406),
 (34, 0.0),
 (35, 0.1675415633166782),
 (36, 0.15897016107942194),
 (37, 0.08549819600709618),
 (38, 0.06494054168326638),
 (39, 0.09453802374948816),
 (40, 0.04682929057908469),
 (41, 0.21341639745917707),
 (42, 0.0),
 (43, 0.08812102431690699),
 (44, 0.03771571432023571),
 (45, 0.06578947368421051),
 (46, 0.17013926184468012),
 (47, 0.2987264917430253),
 (48, 0.09959431881428263),
 (49, 0.03877833671647406),
 (50, 0.07079923254047886),
 (51, 0.09895413919905867),
 (52, 0.22790142204853647),
 (53, 0.11764957176360048),
 (54, 0.01938916835823703),
 (55, 0.04499212706658475),
 (56, 0.24722569302909875),
 (57, 0.06302534916632545),
 (58, 0.045580284409707295),
 (59, 0.054437944538667765),
 (60, 0.011357771260606367),
 (61, 0.25958499574503335),
 (62, 0.04891159880445184),
 (63, 0.08285522649991611),
 (64, 0.064888568452305),
 (65, 0.042601432284230495),
 (66, 0.014451832825401996),
 (67, 0.1946978894863169),
 (68, 0.07733602811121824),
 (69, 0.026871538646250696),
 (70, 0.11712303424679454),
 (71, 0.08193419066805777),
 (72, 0.12725695259515554),
 (73, 0.01911797782254681),
 (74, 0.24678382369818672),
 (75, 0.08456376143646728),
 (76, 0.06424925662032355),
 (77, 0.01981850088223545),
 (78, 0.030934411244487297),
 (79, 0.07894736842105261),
 (80, 0.028878211074619464),
 (81, 0.07950439882424458),
 (82, 0.08031157077540443),
 (83, 0.22213082915965962),
 (84, 0.074215604399294),
 (85, 0.08017658293783157),
 (86, 0.08549819600709618),
 (87, 0.17099639201419237),
 (88, 0.04598545046137244),
 (89, 0.04730472703803727),
 (90, 0.03627381250550058),
 (91, 0.20991342856239587),
 (92, 0.04204138910034078),
 (93, 0.05691103932244722),
 (94, 0.2866297455600074),
 (95, 0.25362863675089403),
 (96, 0.06622661785325219),
 (97, 0.07530940414109723),
 (98, 0.04966996338993915),
 (99, 0.015193428136569098),
 (100, 0.07024393586862705),
 (101, 0.1541517600345829),
 (102, 0.11764957176360048),
 (103, 0.08226127456606226),
 (104, 0.046401616866730944),
 (105, 0.09068453126375145),
 (106, 0.05162257329196673),
 (107, 0.1106817677872384),
 (108, 0.1615552112476628),
 (109, 0.056573571480353566),
 (110, 0.1361331925293325),
 (111, 0.17497830981833887),
 (112, 0.08111071056538126),
 (113, 0.027036903521793755),
 (114, 0.027226638505866502),
 (115, 0.05564148840746572),
 (116, 0.045580284409707295),
 (117, 0.030386856273138196),
 (118, 0.021030505843376807),
 (119, 0.06716604942594676),
 (120, 0.0),
 (121, 0.0734718358370645),
 (122, 0.09304036594559835),
 (123, 0.09464970485606018),
 (124, 0.07530940414109723),
 (125, 0.08433490104000932),
 (126, 0.07530940414109723),
 (127, 0.14429582107316452),
 (128, 0.03498557142706597),
 (129, 0.09334163073596637),
 (130, 0.014013796366780261),
 (131, 0.08849904067559858),
 (132, 0.04204138910034078),
 (133, 0.03121952705272313),
 (134, 0.07647191129018724),
 (135, 0.0),
 (136, 0.015328483487124145),
 (137, 0.020602141085758228),
 (138, 0.11969747440993465),
 (139, 0.07836039099693788),
 (140, 0.041427613249958056),
 (141, 0.16556654463313047),
 (142, 0.05073825686188037),
 (143, 0.07894736842105261),
 (144, 0.07295405746286962),
 (145, 0.07690914705058355),
 (146, 0.05518884821104349),
 (147, 0.11243619908556621),
 (148, 0.05510387687779837),
 (149, 0.2896811091620759),
 (150, 0.2294157338705617),
 (151, 0.12540051368250327),
 (152, 0.04916051440083466),
 (153, 0.0519524333466131),
 (154, 0.03721614637823934),
 (155, 0.025811286645983363),
 (156, 0.14975189244419534),
 (157, 0.06083303292403594),
 (158, 0.3222129681246328),
 (159, 0.056573571480353566),
 (160, 0.07455250649740336),
 (161, 0.059016710652347516),
 (162, 0.059016710652347516),
 (163, 0.06759225880448438),
 (164, 0.05247835714059896),
 (165, 0.056055185467121044),
 (166, 0.10259783520851543),
 (167, 0.059016710652347516),
 (168, 0.19664205760333864),
 (169, 0.1343320988518935),
 (170, 0.08408277820068157),
 (171, 0.04518564248465834),
 (172, 0.11589658124319133),
 (173, 0.031814238148788886),
 (174, 0.09597148699373931),
 (175, 0.04335549847620599),
 (176, 0.014227759830611805),
 (177, 0.021677749238102995),
 (178, 0.016062314155080887),
 (179, 0.04415107856883479),
 (180, 0.013518451760896878),
 (181, 0.02649064714130087),
 (182, 0.08346223261119859),
 (183, 0.05651250986355305),
 (184, 0.3084235851091745),
 (185, 0.10926834468453095),
 (186, 0.043550355630934214),
 (187, 0.10147651372376074),
 (188, 0.047836487323493986),
 (189, 0.07175473098524097),
 (190, 0.06759225880448438),
 (191, 0.04370374100610487),
 (192, 0.08536655898367082),
 (193, 0.06503324771430899),
 (194, 0.015193428136569098),
 (195, 0.051298917604257706),
 (196, 0.07953559537197222),
 (197, 0.05979560915436748),
 (198, 0.03346372407051273),
 (199, 0.06494054168326638),
 (200, 0.16122923187750418),
 (201, 0.01967223688411584),
 (202, 0.018857857160117855),
 (203, 0.08549819600709618),
 (204, 0.028027592733560522),
 (205, 0.03934447376823168),
 (206, 0.1032370802417528),
 (207, 0.12519334891679787),
 (208, 0.12361284651454937),
 (209, 0.03458572319330373),
 (210, 0.07059781184061312),
 (211, 0.04598545046137244),
 (212, 0.04634897746593215),
 (213, 0.05853661322385588),
 (214, 0.0),
 (215, 0.11470786693528086),
 (216, 0.03877833671647406),
 (217, 0.09334163073596637),
 (218, 0.023918243661746993),
 (219, 0.07543142864047142),
 (220, 0.13109470506889243),
 (221, 0.032124628310161774),
 (222, 0.15806712450288418),
 (223, 0.16556654463313047),
 (224, 0.06855106213838522),
 (225, 0.04370374100610487),
 (226, 0.07755667343294811),
 (227, 0.07804881763180782),
 (228, 0.20073876713674155),
 (229, 0.1538057703910978),
 (230, 0.20441907985364974),
 (231, 0.02845551966122361),
 (232, 0.13834289277321493),
 (233, 0.17040572913692198),
 (234, 0.06622661785325218),
 (235, 0.04818694246524266),
 (236, 0.20561572340611634),
 (237, 0.03877833671647406),
 (238, 0.09131087488821056),
 (239, 0.2752988806446741),
 (240, 0.028027592733560522),
 (241, 0.04966996338993915),
 (242, 0.06024752331287778),
 (243, 0.0512989176042577),
 (244, 0.048666426339228755),
 (245, 0.04173111630559929),
 (246, 0.09673016668133488),
 (247, 0.0),
 (248, 0.026669037353133248),
 (249, 0.17040572913692198),
 (250, 0.0),
 (251, 0.07336739820667776),
 (252, 0.011831213107007523),
 (253, 0.09895413919905867),
 (254, 0.044060512158453496),
 (255, 0.0),
 (256, 0.11470786693528087),
 (257, 0.04268327949183541),
 (258, 0.023537557657892522),
 (259, 0.032124628310161774),
 (260, 0.29135827337403253),
 (261, 0.04204138910034078),
 (262, 0.07404360971988654),
 (263, 0.055824219567359015),
 (264, 0.0),
 (265, 0.016912752287293456),
 (266, 0.07596714068284549),
 (267, 0.12695834376925202),
 (268, 0.028903665650803993),
 (269, 0.016062314155080887),
 (270, 0.20138310507789547),
 (271, 0.09637388493048532),
 (272, 0.018857857160117855),
 (273, 0.009304036594559835),
 (274, 0.05887552214709278),
 (275, 0.11969747440993464),
 (276, 0.03498557142706597),
 (277, 0.03568395510523548),
 (278, 0.3311330892662609),
 (279, 0.1251933489167979),
 (280, 0.0),
 (281, 0.03668369910333888),
 (282, 0.03587736549262049),
 (283, 0.012824729401064425),
 (284, 0.012667364798453496),
 (285, 0.012667364798453496),
 (286, 0.06653536832815835),
 (287, 0.014933692277237473),
 (288, 0.016731862035256364),
 (289, 0.03065696697424829),
 (290, 0.03582871819500093),
 (291, 0.06424925662032355),
 (292, 0.06622661785325219),
 (293, 0.016556654463313048),
 (294, 0.09428928580058928),
 (295, 0.06362847629757777),
 (296, 0.03627381250550058),
 (297, 0.05691103932244722),
 (298, 0.0),
 (299, 0.0468292905790847),
 (300, 0.32481131806711666),
 (301, 0.08511306704001456),
 (302, 0.04818694246524266),
 (303, 0.015609763526361564),
 (304, 0.09154684414630487),
 (305, 0.3421708589084696),
 (306, 0.17914359097500465),
 (307, 0.09308574042571362),
 (308, 0.03419927840283847),
 (309, 0.03993615319154359),
 (310, 0.017292861596651866),
 (311, 0.1113498335207611),
 (312, 0.09365858115816939),
 (313, 0.03382550457458691),
 (314, 0.0),
 (315, 0.05374307729250139),
 (316, 0.038474188203193274),
 (317, 0.042601432284230495),
 (318, 0.0),
 (319, 0.08520286456846099),
 (320, 0.08849904067559858),
 (321, 0.0),
 (322, 0.2533558548547658),
 (323, 0.03721614637823934),
 (324, 0.016731862035256364),
 (325, 0.05247835714059896),
 (326, 0.05073825686188037),
 (327, 0.031814238148788886),
 (328, 0.02597621667330655),
 (329, 0.10259783520851541),
 (330, 0.10039117221153819),
 (331, 0.06667259338283311),
 (332, 0.08111071056538126),
 (333, 0.08111071056538126),
 (334, 0.09280323373346189),
 (335, 0.058271654674806495),
 (336, 0.029135827337403247),
 (337, 0.07466846138618737),
 (338, 0.03934447376823168),
 (339, 0.04726901187474408),
 (340, 0.033113308926626096),
 (341, 0.08365931017628181),
 (342, 0.21371260356627755),
 (343, 0.01141385936102632),
 (344, 0.017914359097500464),
 (345, 0.015467205622243648),
 (346, 0.016912752287293456),
 (347, 0.0324442842261525),
 (348, 0.03877833671647406),
 (349, 0.048666426339228755),
 (350, 0.04682929057908469),
 (351, 0.0),
 (352, 0.01860807318911967),
 (353, 0.05098127419345816),
 (354, 0.013157894736842103),
 (355, 0.032961063021678665),
 (356, 0.05374307729250139),
 (357, 0.0),
 (358, 0.05374307729250139),
 (359, 0.01911797782254681),
 (360, 0.08326256191221612),
 (361, 0.046401616866730944),
 (362, 0.12105003117656304),
 (363, 0.11764957176360048),
 (364, 0.014451832825401996),
 (365, 0.13685996549319585),
 (366, 0.06554735253444621),
 (367, 0.0),
 (368, 0.07647191129018724),
 (369, 0.07059781184061312),
 (370, 0.064888568452305),
 (371, 0.10635399695598369),
 (372, 0.06243905410544626),
 (373, 0.380442955126341),
 (374, 0.025334729596906993),
 (375, 0.07059781184061312),
 (376, 0.04370374100610487),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0549351050361311),
 (380, 0.03065696697424829),
 (381, 0.0512989176042577),
 (382, 0.0),
 (383, 0.026315789473684206),
 (384, 0.029135827337403247),
 (385, 0.03539961627023943),
 (386, 0.012905643322991682),
 (387, 0.013157894736842103),
 (388, 0.0),
 (389, 0.11020775375559674),
 (390, 0.03382550457458691),
 (391, 0.06917144638660747),
 (392, 0.016912752287293456),
 (393, 0.015193428136569098),
 (394, 0.014567913668701624),
 (395, 0.05298129428260174),
 (396, 0.026851080677052733),
 (397, 0.03346372407051273),
 (398, 0.0),
 (399, 0.014808721943977306),
 (400, 0.10039117221153819),
 (401, 0.15058675831730728),
 (402, 0.045580284409707295),
 (403, 0.0604563541758343),
 (404, 0.10259783520851541),
 (405, 0.026669037353133248),
 (406, 0.026144349280800103),
 (407, 0.06131393394849658),
 (408, 0.01911797782254681),
 (409, 0.0),
 (410, 0.06282808624375431),
 (411, 0.046401616866730944),
 (412, 0.10280786170305815),
 (413, 0.10926834468453095),
 (414, 0.018367958959266125),
 (415, 0.05348281873006976),
 (416, 0.04518564248465834),
 (417, 0.03673591791853225),
 (418, 0.0899842541331695),
 (419, 0.11846977555181845),
 (420, 0.1007265930331758),
 (421, 0.012369267399882334),
 (422, 0.10375716957991118),
 (423, 0.05407380704358751),
 (424, 0.024738534799764667),
 (425, 0.048098607024388174),
 (426, 0.06653536832815836),
 (427, 0.018857857160117855),
 (428, 0.05395404209689377),
 (429, 0.0),
 (430, 0.1216660658480719),
 (431, 0.015061880828219446),
 (432, 0.2364763257317293),
 (433, 0.01911797782254681),
 (434, 0.0),
 (435, 0.019968076595771794),
 (436, 0.016386838133611553),
 (437, 0.017292861596651866),
 (438, 0.09453802374948816),
 (439, 0.04818694246524266),
 (440, 0.015061880828219446),
 (441, 0.05309942440535914),
 (442, 0.036893922595746136),
 (443, 0.048636038308579745),
 (444, 0.012824729401064425),
 (445, 0.07466846138618737),
 (446, 0.05647824947249049),
 (447, 0.04235868710436787),
 (448, 0.0805532420311582),
 (449, 0.08957179548750233),
 (450, 0.039735970711951306),
 (451, 0.014933692277237473),
 (452, 0.011707322644771175),
 (453, 0.015193428136569098),
 (454, 0.19619314913492364),
 (455, 0.041130637283031124),
 (456, 0.1290564332299168),
 (457, 0.05510387687779837),
 (458, 0.029867384554474945),
 (459, 0.11314714296070713),
 (460, 0.061868822488974594),
 (461, 0.30442954117128224),
 (462, 0.11024280153951839),
 (463, 0.05990422978731538),
 (464, 0.0),
 (465, 0.022075539284417394),
 (466, 0.17660431427533915),
 (467, 0.07169241683455055),
 (468, 0.017099639201419235),
 (469, 0.07175473098524097),
 (470, 0.04598545046137244),
 (471, 0.06759225880448438),
 (472, 0.08549819600709618),
 (473, 0.13006649542861795),
 (474, 0.0),
 (475, 0.05523681766661074),
 (476, 0.10838874619051497),
 (477, 0.0),
 (478, 0.05468482990747588),
 (479, 0.0604563541758343),
 (480, 0.18074256993863336),
 (481, 0.015328483487124145),
 (482, 0.013518451760896878),
 (483, 0.1399422857082639),
 (484, 0.03771571432023571),
 (485, 0.044426165831931916),
 (486, 0.052139939516036765),
 (487, 0.11980845957463077),
 (488, 0.054437944538667765),
 (489, 0.0),
 (490, 0.13497638119975425),
 (491, 0.08658487179917634),
 (492, 0.06765100914917382),
 (493, 0.02995211489365769),
 (494, 0.020277677641345315),
 (495, 0.12695834376925205),
 (496, 0.023537557657892522),
 (497, 0.0),
 (498, 0.05990422978731538),
 (499, 0.0),
 (500, 0.015193428136569098),
 (501, 0.04634897746593215),
 (502, 0.24165972609347458),
 (503, 0.04682929057908469),
 (504, 0.0),
 (505, 0.13382584475782766),
 (506, 0.08111071056538126),
 (507, 0.3231104224953257),
 (508, 0.07664241743562072),
 (509, 0.014933692277237473),
 (510, 0.08193419066805777),
 (511, 0.07443229275647868),
 (512, 0.06554735253444621),
 (513, 0.08885233166386383),
 (514, 0.025811286645983363),
 (515, 0.0324442842261525),
 (516, 0.014686837386151166),
 (517, 0.05098127419345816),
 (518, 0.044060512158453496),
 (519, 0.0),
 (520, 0.0),
 (521, 0.013809204416652685),
 (522, 0.014933692277237473),
 (523, 0.033113308926626096),
 (524, 0.09637388493048532),
 (525, 0.06077371254627639),
 (526, 0.05564148840746572),
 (527, 0.016912752287293456),
 (528, 0.013809204416652685),
 (529, 0.14599927901768628),
 (530, 0.03721614637823934),
 (531, 0.09397878236968457),
 (532, 0.08918325397005952),
 (533, 0.03934447376823168),
 (534, 0.07694837640638655),
 (535, 0.08740748201220974),
 (536, 0.11654330934961299),
 (537, 0.04415107856883479),
 (538, 0.0),
 (539, 0.27912109783679506),
 (540, 0.045580284409707295),
 (541, 0.24366985862022406),
 (542, 0.03754696307413191),
 (543, 0.047721357223183325),
 (544, 0.032773676267223106),
 (545, 0.044426165831931916),
 (546, 0.04055535528269063),
 (547, 0.05510387687779837),
 (548, 0.014227759830611805),
 (549, 0.23308661869922598),
 (550, 0.015467205622243648),
 (551, 0.023662426214015046),
 (552, 0.0),
 (553, 0.016731862035256364),
 (554, 0.0),
 (555, 0.04008829146891578),
 (556, 0.08193419066805777),
 (557, 0.19918863762856526),
 (558, 0.04966996338993915),
 (559, 0.03877833671647406),
 (560, 0.02305714879553582),
 (561, 0.03627381250550058),
 (562, 0.017292861596651866),
 (563, 0.015756337291581362),
 (564, 0.1630554699247529),
 (565, 0.04335549847620599),
 (566, 0.012905643322991682),
 (567, 0.016062314155080887),
 (568, 0.1183892660110542),
 (569, 0.04598545046137244),
 (570, 0.041204282171516456),
 (571, 0.10705186531570646),
 (572, 0.06622661785325218),
 (573, 0.024318019154289872),
 (574, 0.014227759830611805),
 (575, 0.07169241683455055),
 (576, 0.046401616866730944),
 (577, 0.30588764516074896),
 (578, 0.02488363008967197),
 (579, 0.1749783098183389),
 (580, 0.014338483366910109),
 (581, 0.23288666826750604),
 (582, 0.29314232661238443),
 (583, 0.03568395510523548),
 (584, 0.07336739820667776),
 (585, 0.10729938440986901),
 (586, 0.10012523486435176),
 (587, 0.13809204416652687),
 (588, 0.017292861596651866),
 (589, 0.11615078990692514),
 (590, 0.01911797782254681),
 (591, 0.0645282166149584),
 (592, 0.11615078990692514),
 (593, 0.03668369910333888),
 (594, 0.028239124736245246),
 (595, 0.25387276871303704),
 (596, 0.059234887775909226),
 (597, 0.033113308926626096),
 (598, 0.04415107856883479),
 (599, 0.10814761408717502),
 (600, 0.046401616866730944),
 (601, 0.04055535528269063),
 (602, 0.061868822488974594),
 (603, 0.03065696697424829),
 (604, 0.03877833671647406),
 (605, 0.016386838133611553),
 (606, 0.02282771872205264),
 (607, 0.074215604399294),
 (608, 0.0),
 (609, 0.04204138910034078),
 (610, 0.0691073690718941),
 (611, 0.058271654674806495),
 (612, 0.057353933467640436),
 (613, 0.01938916835823703),
 (614, 0.028676966733820218),
 (615, 0.029135827337403247),
 (616, 0.01938916835823703),
 (617, 0.14912022701586516),
 (618, 0.08371385281611447),
 (619, 0.0),
 (620, 0.0),
 (621, 0.051298917604257706),
 (622, 0.013710212427677042),
 (623, 0.015328483487124145),
 (624, 0.09428928580058928),
 (625, 0.04818694246524266),
 (626, 0.17920430732684967),
 (627, 0.08365931017628181),
 (628, 0.14273582042094193),
 (629, 0.028239124736245246),
 (630, 0.030386856273138196),
 (631, 0.034412360080584264),
 (632, 0.10147651372376074),
 (633, 0.11615078990692515),
 (634, 0.07664241743562072),
 (635, 0.09462916232627815),
 (636, 0.013809204416652685),
 (637, 0.030934411244487297),
 (638, 0.03934447376823168),
 (639, 0.015467205622243648),
 (640, 0.0402766210155791),
 (641, 0.0),
 (642, 0.14227759830611805),
 (643, 0.18560646746692377),
 (644, 0.029867384554474945),
 (645, 0.026669037353133248),
 (646, 0.06424925662032355),
 (647, 0.056055185467121044),
 (648, 0.016062314155080887),
 (649, 0.0),
 (650, 0.044801076831712416),
 (651, 0.0),
 (652, 0.02761840883330537),
 (653, 0.07543142864047142),
 (654, 0.06748819059987712),
 (655, 0.04682929057908469),
 (656, 0.014013796366780261),
 (657, 0.04521000789084244),
 (658, 0.039216523921200154),
 (659, 0.014808721943977306),
 (660, 0.10138838820672658),
 (661, 0.2838874869788344),
 (662, 0.0),
 (663, 0.0),
 (664, 0.03582871819500093),
 (665, 0.04370374100610487),
 (666, 0.10039117221153818),
 (667, 0.0),
 (668, 0.07755667343294811),
 (669, 0.020942695414584774),
 (670, 0.05967860100145693),
 (671, 0.056055185467121044),
 (672, 0.016731862035256364),
 (673, 0.03647702873143481),
 (674, 0.08278327231656524),
 (675, 0.0468292905790847),
 (676, 0.015756337291581362),
 (677, 0.08111071056538127),
 (678, 0.07647191129018724),
 (679, 0.0),
 (680, 0.16289594138375035),
 (681, 0.04966996338993915),
 (682, 0.012667364798453496),
 (683, 0.03012376165643889),
 (684, 0.04055535528269063),
 (685, 0.01967223688411584),
 (686, 0.056573571480353566),
 (687, 0.09832102880166932),
 (688, 0.040555355282690636),
 (689, 0.0),
 (690, 0.02445579940222592),
 (691, 0.044801076831712416),
 (692, 0.23475647508309563),
 (693, 0.015756337291581362),
 (694, 0.02488363008967197),
 (695, 0.04966996338993915),
 (696, 0.026315789473684206),
 (697, 0.0),
 (698, 0.043015450100730324),
 (699, 0.02341464528954235),
 (700, 0.015609763526361564),
 (701, 0.056573571480353566),
 (702, 0.012159009577144936),
 (703, 0.013518451760896878),
 (704, 0.09197090092274487),
 (705, 0.014686837386151166),
 (706, 0.014338483366910109),
 (707, 0.0),
 (708, 0.032124628310161774),
 (709, 0.053702161354105465),
 (710, 0.03627381250550058),
 (711, 0.032773676267223106),
 (712, 0.013809204416652685),
 (713, 0.048098607024388174),
 (714, 0.0),
 (715, 0.08111071056538126),

In [92]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2409, 0.49356764739637354),
 (4336, 0.4113063728303113),
 (1537, 0.38807121827489494),
 (3162, 0.3879852850993631),
 (373, 0.380442955126341)]

In [98]:
def recommend(movie):
    movie_index=final_df[final_df['title']==movie].index[0]
    distances=similarity[movie_index]
    #sort these distances and extract the top 5 movies
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
#         print(i[0])
        print(final_df.iloc[i[0]].title)

In [99]:
recommend('Avatar')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [100]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [101]:
import pickle

In [102]:
pickle.dump(final_df,open('movies.pkl','wb'))

In [104]:
final_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [105]:
pickle.dump(similarity,open('similarity.pkl','wb'))